Update menu_inst

diff --git a/menu_inst b/menu_inst
--- a/menu_inst
+++ b/menu_inst
@@ -1253,9 +1253,19 @@ echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪�
 port_
 echo -e "${cor[1]} ▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪▪ \033[1;37m"
 read -p " Local-Port: " portserv
-if [[ -z "${portserv}" ]];then
-    portserv=22
-fi
+         while true; do
+         echo -ne "\033[1;37m"
+	 echo " Ingresa el Puerto Local de tu VPS (Default 22) "
+         read -p " Local-Port: " portserv
+         if [[ ! -z $portx ]]; then
+	     	portserv=22
+         else
+	 	if [[ $(echo $portserv|grep [0-9]) ]]; then
+			[[ $(mportas|grep $portserv) ]] && break || echo -e "\033[1;31m $(source trans -b pt:${id} "Puerto Invalido")"
+		fi
+	 fi
+	 
+         done
 echo -e "\033[1;33m $(source trans -b pt:${id} "Digite el Puerto SSL, que Va a USAR:")"
 echo " Ingresa Nuevo Puerto SSL/TLS a USAR (Recomendado 110-442-444)  "
 read -p " Listen-SSL: " portssl
