Update menu_inst

diff --git a/menu_inst b/menu_inst
--- a/menu_inst
+++ b/menu_inst
@@ -29,16 +29,16 @@ fun_eth () {
 eth=$(ifconfig | grep -v inet6 | grep -v lo | grep -v 127.0.0.1 | grep "encap:Ethernet" | awk '{print $1}')
     [[ $eth != "" ]] && {
     echo -e "$barra"
-    echo -e "${cor[3]} $(source trans -b pt:${id} "Aplicar Sistema Para Mejorar Sistema SSH?")"
-    echo -e "${cor[3]} $(source trans -b pt:${id} "Opcion Para Usuarios Avanzados")"
+    echo -e "${cor[3]} $(source trans -b pt:${id} "Aplicar Sistema Para Melhorar Pacotes Ssh?")"
+    echo -e "${cor[3]} $(source trans -b pt:${id} "Opcao Para Usuarios Avancados")"
     echo -e "$barra"
     read -p " [S/N]: " -e -i n sshsn
            [[ "$sshsn" = @(s|S|y|Y) ]] && {
-           echo -e "${cor[1]} $(source trans -b pt:${id} "Correcion de problemas de paquetes en SSH...")"
-           echo -e " $(source trans -b pt:${id} "Quota en Entrada")"
+           echo -e "${cor[1]} $(source trans -b pt:${id} "Correcao de problemas de pacotes no SSH...")"
+           echo -e " $(source trans -b pt:${id} "Qual A Taxa RX")"
            echo -ne "[ 1 - 999999999 ]: "; read rx
            [[ "$rx" = "" ]] && rx="999999999"
-           echo -e " $(source trans -b pt:${id} "Quota en Salida")"
+           echo -e " $(source trans -b pt:${id} "Qual A Taxa TX")"
            echo -ne "[ 1 - 999999999 ]: "; read tx
            [[ "$tx" = "" ]] && tx="999999999"
            apt-get install ethtool -y > /dev/null 2>&1
@@ -94,12 +94,12 @@ fun_squid  () {
   return 0
   }
 #Instalar
-echo -e "$barra\n\033[1;32m $(source trans -b pt:${id} "INSTALADOR SQUID ChumoGH-Script")\n$barra"
+echo -e "$barra\n\033[1;32m $(source trans -b pt:${id} "INSTALADOR SQUID ADM-ULTIMATE")\n$barra"
 fun_ip
 echo -ne " $(source trans -b pt:${id} "Confirme seu ip")"; read -p ": " -e -i $IP ip
-echo -e "$barra\n $(source trans -b pt:${id} "Ahora Escoja su Puerto que Desea en Squid")"
-echo -e " $(source trans -b pt:${id} "Escoja su Puerto, Ejemplo: 80 8080 3128")"
-echo -ne " $(source trans -b pt:${id} "Digite su Portas:") "; read portasx
+echo -e "$barra\n $(source trans -b pt:${id} "Agora Escolha as Portas que Deseja No Squid")"
+echo -e " $(source trans -b pt:${id} "Escolha As Portas, Exemplo: 80 8080 3128")"
+echo -ne " $(source trans -b pt:${id} "Digite as Portas:") "; read portasx
 echo -e "$barra"
 totalporta=($portasx)
 unset PORT
@@ -131,7 +131,7 @@ echo -e " ${txt[220]}"
 read -p " $(source trans -b es:${id} "Agregar Host"): " hos
 if [[ $hos != \.* ]]; then
 echo -e "$barra"
-echo -e "\033[1;31m $(source trans -b es:${id} " [!] Host-Squid debe iniciar con un "."")\033[0m"
+echo -e "\033[1;31m $(source trans -b es:${id} " [!] Host-Squid debe iniciar con "."")\033[0m"
 echo -e "\033[1;31m $(source trans -b es:${id} " Asegurese de agregarlo despues corretamente!")\033[0m"
 fi
 host="$hos/"
@@ -276,22 +276,21 @@ done
 }
 
 fun_dropbear () {
-read -p " Listen-DROPBEAR: " dpa
  [[ -e /etc/default/dropbear ]] && {
  echo -e "$barra\n\033[1;32m $(source trans -b es:${id} "REMOVIENDO DROPBEAR")\n$barra"
  fun_bar "apt-get remove dropbear -y"
  echo -e "$barra\n\033[1;32m $(source trans -b pt:${id} "Dropbear Removido")\n$barra"
  [[ -e /etc/default/dropbear ]] && rm /etc/default/dropbear
- user -k $dpa/tcp > /dev/null 2>&1
+ user -k 443/tcp > /dev/null 2>&1
  return 0
  }
 echo -e "$barra\n\033[1;32m $(source trans -b pt:${id} "INSTALADOR DROPBEAR ADM-ULTIMATE")\n$barra"
-echo -e " $(source trans -b es:${id} "DROPBEAR USA EL PUERTO " $dpa)\033[1;37m"
+echo -e " $(source trans -b es:${id} "DROPBEAR USA EL PUERTO 443")\033[1;37m"
 echo -e "$barra"
-   [[ $(mportas|grep $dpa) != "" ]] && {
-   echo -e "\033[1;31m $(source trans -b pt:${id} "PORTA " $dpa "EN USO")\033[1;37m"
+   [[ $(mportas|grep 443) != "" ]] && {
+   echo -e "\033[1;31m $(source trans -b pt:${id} "PORTA 443 EM USO")\033[1;37m"
    echo -e "\033[1;31m $(source trans -b es:${id} "INTENTE NUEVAMENTE")\033[1;37m"
-   fuser -k $dpa/tcp > /dev/null 2>&1
+   fuser -k 443/tcp > /dev/null 2>&1
    echo -e "$barra"
    return 1
    }
@@ -332,7 +331,7 @@ echo -e "$barra"
 touch /etc/dropbear/banner
 echo -e "${cor[2]} $(source trans -b pt:${id} "Configurando dropbear")"
 echo -e "NO_START=0" > /etc/default/dropbear
-echo -e 'DROPBEAR_EXTRA_ARGS="-p '$dpa'"' >> /etc/default/dropbear
+echo -e 'DROPBEAR_EXTRA_ARGS="-p 443"' >> /etc/default/dropbear
 echo -e 'DROPBEAR_BANNER="/etc/dropbear/banner"' >> /etc/default/dropbear
 echo -e "DROPBEAR_RECEIVE_WINDOW=65536" >> /etc/default/dropbear
 } || {
@@ -363,21 +362,20 @@ AcceptEnv LANG LC_*
 Subsystem sftp /usr/lib/openssh/sftp-server
 UsePAM yes" > /etc/ssh/sshd_config
 echo -e "${cor[2]} $(source trans -b pt:${id} "Instalando dropbear")"
-read -p " Listen-DROPBEAR: " dpa
 echo -e "$barra"
 fun_bar "apt-get install dropbear -y"
-cat /etc/bannerssh > /etc/dropbear/banner
+touch /etc/dropbear/banner
 echo -e "$barra"
 echo -e "${cor[2]} $(source trans -b pt:${id} "Configurando dropbear")"
 echo -e "NO_START=0" > /etc/default/dropbear
-echo -e 'DROPBEAR_EXTRA_ARGS="-p '$dpa'"' >> /etc/default/dropbear
-echo -e 'DROPBEAR_BANNER="/etc/bannerssh"' >> /etc/default/dropbear
+echo -e 'DROPBEAR_EXTRA_ARGS="-p 443"' >> /etc/default/dropbear
+echo -e 'DROPBEAR_BANNER="/etc/dropbear/banner"' >> /etc/default/dropbear
 echo -e "DROPBEAR_RECEIVE_WINDOW=65536" >> /etc/default/dropbear
 }
 fun_eth
 service ssh restart > /dev/null 2>&1
 service dropbear restart > /dev/null 2>&1
-echo -e "$barra\n${cor[3]} $(source trans -b pt:${id} "Dropbear Configurado Exitosamente")\n$barra"
+echo -e "$barra\n${cor[3]} $(source trans -b pt:${id} "Seu dropbear foi configurado com sucesso")\n$barra"
 mportas > /tmp/portz
 while read portas; do
 [[ $portas = "" ]] && break
@@ -1065,11 +1063,11 @@ return 0
 ssl_stunel () {
 [[ $(mportas|grep stunnel4|head -1) ]] && {
 echo -e "$barra"
-echo -e "\033[1;33m $(source trans -b pt:${id} "Cerrando PUERTO SSL/TLS")"
+echo -e "\033[1;33m $(source trans -b pt:${id} "Parando Stunnel")"
 echo -e "$barra"
 fun_bar "apt-get purge stunnel4 -y"
 echo -e "$barra"
-echo -e "\033[1;33m $(source trans -b pt:${id} "PUERTO SSL/TLS CERRADO!")"
+echo -e "\033[1;33m $(source trans -b pt:${id} "Parado Com Sucesso!")"
 echo -e "$barra"
 return 0
 }
@@ -1084,13 +1082,13 @@ echo -e "$barra"
          read -p " Local-Port: " portx
          if [[ ! -z $portx ]]; then
              if [[ $(echo $portx|grep [0-9]) ]]; then
-                [[ $(mportas|grep $portx|head -1) ]] && break || echo -e "\033[1;31m $(source trans -b pt:${id} "Puerto Invalido")"
+                [[ $(mportas|grep $portx|head -1) ]] && break || echo -e "\033[1;31m $(source trans -b pt:${id} "Porta Invalida")"
              fi
          fi
          done
 echo -e "$barra"
 DPORT="$(mportas|grep $portx|awk '{print $2}'|head -1)"
-echo -e "\033[1;33m $(source trans -b pt:${id} "Digite el Puerto SSL, que Va a USAR:")"
+echo -e "\033[1;33m $(source trans -b pt:${id} "Agora Presizamos Saber Qual Porta o SSL, Vai Escutar")"
 echo -e "$barra"
     while true; do
     read -p " Listen-SSL: " SSLPORT
@@ -1101,17 +1099,17 @@ echo -e "$barra"
 	return 0
     done
 echo -e "$barra"
-echo -e "\033[1;33m $(source trans -b pt:${id} "Instalando SSL/TLS")"
+echo -e "\033[1;33m $(source trans -b pt:${id} "Instalando SSL")"
 echo -e "$barra"
 fun_bar "apt-get install stunnel4 -y"
 echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:${DPORT}\naccept = ${SSLPORT}" > /etc/stunnel/stunnel.conf
 openssl genrsa -out key.pem 2048 > /dev/null 2>&1
-(echo "EC"; echo "@ChumoGH"; echo "@ChumoGH"; echo "+593987072611"; echo "@ChumoGH"; echo "ECUADOR"; echo "chumogh@gmail.com")|openssl req -new -x509 -key key.pem -out cert.pem -days 1095 > /dev/null 2>&1
+(echo br; echo br; echo uss; echo speed; echo adm; echo ultimate; echo @admultimate)|openssl req -new -x509 -key key.pem -out cert.pem -days 1095 > /dev/null 2>&1
 cat key.pem cert.pem >> /etc/stunnel/stunnel.pem
 sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
 service stunnel4 restart > /dev/null 2>&1
 echo -e "$barra"
-echo -e "\033[1;33m $(source trans -b pt:${id} "INSTALADO EXITOSA")"
+echo -e "\033[1;33m $(source trans -b pt:${id} "INSTALADO COM SUCESSO")"
 echo -e "$barra"
 return 0
 }
@@ -1222,10 +1220,10 @@ unset ddos
 echo -e "$barra"
 echo -e "${cor[5]} ${txt[335]}"
 echo -e "$barra"
-echo -e "${cor[2]} [1] > ${cor[3]}SQUID / gzip $squid"
-echo -e "${cor[2]} [2] > ${cor[3]}DROPBEAR HTTP/HTTPS $dropbear"
+echo -e "${cor[2]} [1] > ${cor[3]}SQUID $squid"
+echo -e "${cor[2]} [2] > ${cor[3]}DROPBEAR $dropbear"
 echo -e "${cor[2]} [3] > ${cor[3]}OPENVPN $openvpn"
-echo -e "${cor[2]} [4] > ${cor[3]}SSL/TLS TUNNEL $stunel"
+echo -e "${cor[2]} [4] > ${cor[3]}SSL TUNNEL $stunel"
 echo -e "${cor[2]} [5] > ${cor[3]}SHADOW SOCKS $shadow"
 echo -e "${cor[2]} [6] > ${cor[3]}PROXY SOCKS $socks"
 echo -e "${cor[2]} [7] > ${cor[3]}PROXY GETTUNEL $gettun"
