Update menu

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -240,6 +240,14 @@ swapoff -a && swapon -a 1> /dev/null 2> /dev/null
 echo 3 > /proc/sys/vm/drop_caches
 sysctl -w vm.drop_caches=3 > /dev/null 2>&1
 rm -rf /tmp/*
+##
+echo -ne " \033[1;31m[ ! ] Services BadVPN restart" >> /root/lm.log
+kill -9 $(ps x | grep badvpn | grep -v grep | awk '{print $1'}) > /dev/null 2>&1
+killall badvpn-udpgw > /dev/null 2>&1
+unset pid_badvpn
+[[ -e /bin/badvpn-udpgw ]] && screen -dmS screen /bin/badvpn-udpgw --listen-addr 127.0.0.1:7300 --max-clients 1000 --max-connections-for-client 10 > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+pid_badvpn=$(ps x | grep badvpn | grep -v grep | awk '{print $1}')
+##
 echo -ne " \033[1;31m[ ! ] Services stunnel4 restart"
 service stunnel4 restart > /dev/null 2>&1
 [[ -e /etc/init.d/stunnel4 ]] && /etc/init.d/stunnel4 restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
