Update menu

diff --git a/menu b/menu
--- a/menu
+++ b/menu
@@ -205,7 +205,130 @@ echo -e "\033[1;37m › /etc/shadowsocks-r/config.json\033[0m"
 cat /etc/shadowsocks-r/config.json
 echo -e "[\033[1;31m-\033[1;33m]\033[1;30m =======================================\033[1;33m"
 }
+##
+update_pak () {
+echo -ne " \033[1;31m[ ! ] apt-get update"
+apt-get update -y > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] apt-get upgrade"
+apt-get upgrade -y > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+msg -bar
+return
+}
 
+reiniciar_ser () {
+echo -ne " \033[1;31m[ ! ] Services stunnel4 restart"
+service stunnel4 restart > /dev/null 2>&1
+[[ -e /etc/init.d/stunnel4 ]] && /etc/init.d/stunnel4 restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services squid restart"
+service squid restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services squid3 restart"
+service squid3 restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services apache2 restart"
+service apache2 restart > /dev/null 2>&1
+[[ -e /etc/init.d/apache2 ]] && /etc/init.d/apache2 restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services openvpn restart"
+service openvpn restart > /dev/null 2>&1
+[[ -e /etc/init.d/openvpn ]] && /etc/init.d/openvpn restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services dropbear restart"
+service dropbear restart > /dev/null 2>&1
+[[ -e /etc/init.d/dropbear ]] && /etc/init.d/dropbear restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services ssh restart"
+service ssh restart > /dev/null 2>&1
+[[ -e /etc/init.d/ssh ]] && /etc/init.d/ssh restart > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+echo -ne " \033[1;31m[ ! ] Services fail2ban restart"
+( 
+[[ -e /etc/init.d/ssh ]] && /etc/init.d/ssh restart
+fail2ban-client -x stop && fail2ban-client -x start
+) > /dev/null 2>&1 && echo -e "\033[1;32m [OK]" || echo -e "\033[1;31m [FAIL]"
+msg -bar
+return
+}
+
+reiniciar_vps () {
+echo -ne " \033[1;31m[ ! ] Sudo Reboot"
+sleep 3s
+echo -e "\033[1;32m [OK]"
+(
+sudo reboot
+) > /dev/null 2>&1
+msg -bar
+return
+}
+
+host_name () {
+unset name
+while [[ ${name} = "" ]]; do
+echo -ne "\033[1;37m $(fun_trans "Nuevo nombre del host"): " && read name
+tput cuu1 && tput dl1
+done
+hostnamectl set-hostname $name 
+if [ $(hostnamectl status | head -1  | awk '{print $3}') = "${name}" ]; then 
+echo -e "\033[1;33m $(fun_trans "Host alterado corretamente")!, $(fun_trans "reiniciar VPS")"
+else
+echo -e "\033[1;33m $(fun_trans "Host no modificado")!"
+fi
+return
+}
+
+cambiopass () {
+echo -e "${cor[3]} $(fun_trans "Esta herramienta cambia la contraseña de su servidor vps")"
+echo -e "${cor[3]} $(fun_trans "Esta contraseña es utilizada como usuario") root"
+msg -bar
+echo -ne " $(fun_trans "Desea Seguir?") [S/N]: "; read x
+[[ $x = @(n|N) ]] && msg -bar && return
+msg -bar
+#Inicia Procedimentos
+echo -e "${cor[0]} $(fun_trans "Escriba su nueva contraseña")"
+read  -p " Nuevo passwd: " pass
+(echo $pass; echo $pass)|passwd 2>/dev/null
+sleep 1s
+echo -e "${cor[3]} $(fun_trans "Contraseña cambiada con exito!")"
+echo -e "${cor[2]} $(fun_trans "Su contraseña ahora es"): ${cor[4]}$pass"
+return
+}
+
+rootpass () {
+clear
+msg -bar
+echo -e "${cor[3]}  Esta herramienta cambia a usuario root las VPS de "
+echo -e "${cor[3]}             GoogleCloud y Amazon"
+msg -bar
+echo -ne " Desea Seguir? [S/N]: "; read x
+[[ $x = @(n|N) ]] && msg -bar && return
+#Inicia Procedimentos
+echo -e "                 Aplicando Configuraciones"
+fun_bar "service ssh restart"
+#Parametros Aplicados
+sed -i "s;PermitRootLogin prohibit-password;PermitRootLogin yes;g" /etc/ssh/sshd_config
+sed -i "s;PermitRootLogin without-password;PermitRootLogin yes;g" /etc/ssh/sshd_config
+sed -i "s;PasswordAuthentication no;PasswordAuthentication yes;g" /etc/ssh/sshd_config
+msg -bar
+echo -e "Escriba su contraseña root actual o cambiela"
+read  -p " Nuevo passwd: " pass
+(echo $pass; echo $pass)|passwd 2>/dev/null
+sleep 1s
+fun_bar
+echo -e "${cor[3]} Configuraciones aplicadas con exito!"
+echo -e "${cor[2]} Su contraseña ahora es: ${cor[4]}$pass"
+service ssh restart > /dev/null 2>&1
+#msg -bar
+return
+}
+
+
+pamcrack () {
+echo -e "Liberar passwd para VURTL"
+echo -ne " $(fun_trans "Desea Seguir?") [S/N]: "; read x
+[[ $x = @(n|N) ]] && fun_bar && return
+echo -e ""
+fun_bar "service ssh restart"
+sed -i 's/.*pam_cracklib.so.*/password sufficient pam_unix.so sha512 shadow nullok try_first_pass #use_authtok/' /etc/pam.d/common-password
+fun_bar "service ssh restart"
+echo -e ""
+echo -e " \033[1;31m[ ! ]\033[1;33mConfiguraciones VURTL aplicadas"
+#msg -bar
+return
+}
 
 #FUNCIONES
 
@@ -343,11 +466,16 @@ clear
 source cabecalho
 echo -e "${cor[1]} ➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶➶ ${cor[0]}"
 echo -e "${cor[2]} \033[1;32mMenu de Administracion de Puertos"
-echo -e "${cor[2]} 0] > \033[1;31mVolver"
-echo -e "${cor[2]} 1] > \033[1;31mDetener Puertos"
-echo -e "${cor[2]} 2] > \033[1;31mDesinstalar Puerto."
-echo -e "${cor[2]} 3] > \033[1;31mIniciar Puerto."
-echo -e "${cor[2]} 4] > \033[1;31mMostrar Configuraciones"
+echo -e "${cor[2]} [0] > \033[1;31mVolver"
+echo -e "${cor[2]} [1] > \033[1;31mREINICIAR Servicios"
+echo -e "${cor[2]} [2] > \033[1;31mDesinstalar Servicios de Puertos."
+echo -e "${cor[2]} [3] > \033[1;31mCambiar ROOT PassWD."
+echo -e "${cor[2]} [4] > \033[1;31mMostrar Configuraciones de Puertos"
+echo -e "${cor[2]} [5] > \033[1;36mACTULIZAR VPS"
+echo -e "${cor[2]} [6] > \033[1;36mREINICIAR SERVICIOS"
+echo -e "${cor[2]} [7] > \033[1;36mREINICIAR VPS"
+echo -e "${cor[2]} [8] > \033[1;36mCAMBIAR HOSTNAME VPS"
+echo -e "${cor[2]} [9] > \033[1;36mFIX CONTRASEÑA ROOT EN AMAZON & GG CLOUD"
 echo -e "${cor[1]} ➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷➷ ${cor[0]}"
 read -p " Escoje " ppp
 case $ppp in
@@ -361,45 +489,15 @@ case $ppp in
 	figlet -p -f slant < /root/name | lolcat
 		echo -e "\033[1;37m      【     ★ ChumoGH Packet 2020 ★     】\033[0m"
 		echo -e "[\033[1;31m-\033[1;33m]\033[1;31m #######################################\033[1;33m"
-		echo -e "\033[1;37mSeleccione una opcion a Detener:    Para Salir Ctrl + C\033[1;33m
-		[\033[1;30m1\033[1;33m] BADVPN \033[1;33m
-		[\033[1;30m2\033[1;33m] FAIL2BAN \033[1;33m
-		[\033[1;30m3\033[1;33m] STUNNEL4 \033[1;33m
-		[\033[1;30m4\033[1;33m] WEBMIN \033[1;33m
-		[\033[1;30m5\033[1;33m] PYTHON \033[1;33m
-		[\033[1;30m6\033[1;33m] SHADOWSOCKS \033[1;33m
-		[\033[1;30m7\033[1;33m] DROPBEAR \033[1;33m
-		[\033[1;30m8\033[1;33m] OPENVPN \033[1;33m
-		[\033[1;30m9\033[1;33m] LIBRERIAS 32BITS \033[1;33m
-		[\033[1;30m10\033[1;33m] NGINX \033[1;33m
-		[\033[1;30m11\033[1;33m] SQUID \033[1;33m
-		[\033[1;30m12\033[1;33m] V2RAY \033[1;33m
+		echo -e "\033[1;37mSeleccione una opcion :    Para Salir Ctrl + C\033[1;33m
+		[\033[1;30m1\033[1;33m] REINICIAR SERVICIOS \033[1;33m
 		[\033[1;30m0\033[1;33m] < REGRESAR \033[1;33m"
 		read -p ": " opcao
 		case $opcao in
 		1)
-		source menu;;
+		reiniciar_ser
+		break;;
 		2)
-		source menu;;
-		3)
-		source menu;;
-		4)
-		source menu;;
-		5)
-		source menu;;
-		6)
-		source menu;;
-		7)
-		source menu;;
-		8)
-		source menu;;
-		9)
-		source menu;;
-		10)
-		source menu;;
-		11)
-		source menu;;
-		12)
 		source menu;;
 		0)
 		source menu;;
@@ -460,9 +558,8 @@ case $ppp in
 	clear
 	figlet ChumoGH
 	echo -e "${cor[2]} \033[1;32mFUNCION EN DISEÑO" $ppp
-	source menu
-	exit
-	;;
+	cambiopass
+	break;;
 	4)
 		figlet -p -f slant < /root/name | lolcat
 		echo -e "\033[1;37m      【     ★ ChumoGH Packet 2020 ★     】\033[0m"
@@ -504,6 +601,20 @@ case $ppp in
 		esac
 		
 	;;
+	5)
+	update_pak
+	break;;
+	6)
+	reiniciar_ser
+	break;;
+	7)
+	;;
+	8)
+	host_name
+	break;;
+	9)
+	rootpass
+	break;;
 	*)
 	source menu
 	;;
