Update menu_inst

diff --git a/menu_inst b/menu_inst
--- a/menu_inst
+++ b/menu_inst
@@ -1474,6 +1474,7 @@ case $lang in
 source <(curl -sL https://raw.githubusercontent.com/ChumoGH/ChumoGH-Script/master/ssl)
 ;;
 2)
+sshports=`netstat -tunlp | grep sshd | grep 0.0.0.0: | awk '{print substr($4,9); }' > /tmp/ssh.txt && echo | cat /tmp/ssh.txt | tr '\n' ' ' > /etc/adm-lite/sshports.txt && cat /etc/adm-lite/sshports.txt`;
 echo -e "$barra"
 echo -e "\033[1;36m $(source trans -b pt:${id} "SSL Stunnel")"
 echo -e "$barra"
@@ -1486,7 +1487,9 @@ echo -e "$barra"
          read -p " Local-Port: " portx
          if [[ ! -z $portx ]]; then
              if [[ $(echo $portx|grep [0-9]) ]]; then
-                [[ $(mportas|grep $portx|head -1) ]] && break || echo -e "\033[1;31m $(source trans -b pt:${id} "Puerto Invalido")"
+                [[ $(mportas|grep $portx|head -1) ]] && break || echo -e "\033[1;31m $(source trans -b pt:${id} "Puerto Invalido, Buscaremos SSH") "
+		portx=$sshports
+		break
              fi
          fi
          done
@@ -1508,9 +1511,9 @@ echo -e "$barra"
 echo -e "\033[1;33m $(source trans -b pt:${id} "Instalando SSL/TLS")"
 echo -e "$barra"
 fun_bar "apt-get install stunnel4 -y"
-echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[stunnel]\nconnect = 127.0.0.1:${DPORT}\naccept = ${SSLPORT}" > /etc/stunnel/stunnel.conf
+echo -e "cert = /etc/stunnel/stunnel.pem\nclient = no\nsocket = a:SO_REUSEADDR=1\nsocket = l:TCP_NODELAY=1\nsocket = r:TCP_NODELAY=1\n\n[ssh]\nconnect = 127.0.0.1:${sshports}\naccept = ${SSLPORT}" > /etc/stunnel/stunnel.conf
 openssl genrsa -out key.pem 2048 > /dev/null 2>&1
-(echo "EC"; echo "ChumoGH-Script"; echo "VPS-Premium"; echo "www.m.chumogh.xyz"; echo "+593987072611"; echo "ECUADOR"; echo "chumogh@gmail.com")|openssl req -new -x509 -key key.pem -out cert.pem -days 1095 > /dev/null 2>&1
+(echo "EC"; echo "ChumoGH-ADM"; echo "VPS-Premium"; echo "ADM-2021"; echo "+593987072611"; echo "ECUADOR"; echo "chumogh@gmail.com")|openssl req -new -x509 -key key.pem -out cert.pem -days 1095 > /dev/null 2>&1
 cat key.pem cert.pem >> /etc/stunnel/stunnel.pem
 sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
 service stunnel4 restart > /dev/null 2>&1
@@ -1520,8 +1523,6 @@ echo 3 > /proc/sys/vm/drop_caches 1> /dev/null 2> /dev/null
 sysctl -w vm.drop_caches=3 1> /dev/null 2> /dev/null
 swapoff -a && swapon -a 1> /dev/null 2> /dev/null
 service ssh restart 1> /dev/null 2> /dev/null
-service squid restart 1> /dev/null 2> /dev/null
-service squid3 restart 1> /dev/null 2> /dev/null
 echo -e "\033[1;34m ##############################"
 echo -e "\033[1;37m R E I N I C I A N D O  -  STUNNEL4 - SSL"
 echo -e "\033[1;34m ##############################"
